[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "app"
version = "0.0.1"

dependencies = [
    "faststream[kafka, docs]>=0.1.3",
]

[project.optional-dependencies]
dev = [
    "faststream[kafka, testing]>=0.1.3",
]
